In [1]:
import pandas as pd
import numpy as np



df = pd.read_csv(
    "DataSetLimpio.csv",
    sep=",",
    encoding="utf-8-sig"   # elimina el BOM (\ufeff) del inicio
)

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 805243 entries, 0 to 805242
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      805243 non-null  int64
 1   StockCode    805243 non-null  str
 2   Description  805243 non-null  str
 3   Quantity     805243 non-null  int64
 4   InvoiceDate  805243 non-null  str
 5   Price        805243 non-null  float64
 6   Customer ID  805243 non-null  float64
 7   Country      805243 non-null  str
 8   Total        805243 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 55.3 MB

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [4]:
import pandas as pd

df1 = pd.read_csv("DataSetLimpio.csv")
df2 = pd.read_csv("DataSetLimpio_V2.csv")

print("="*70)
print("COMPARACIÓN DE DATASETS")
print("="*70)

# Dimensiones
print("\nDimensiones")
print("-----------------------------")
print("DataSetLimpio.csv        :", df1.shape)
print("DataSetLimpio_V2   :", df2.shape)

# Columnas
print("\nColumnas")
print("-----------------------------")

cols1 = set(df1.columns)
cols2 = set(df2.columns)

print("Columnas iguales:", cols1 == cols2)

print("Solo en DataSetLimpio:")
print(cols1 - cols2)

print("Solo en DataSetLimpio_V2:")
print(cols2 - cols1)

# Tipos de datos
print("\nTipos de datos")
print("-----------------------------")

display(pd.DataFrame({
    "DataSetLimpio": df1.dtypes,
    "DataSetLimpio_V2": df2.dtypes
}))

# Nulos
print("\nValores nulos")
print("-----------------------------")

display(pd.DataFrame({
    "DataSetLimpio": df1.isna().sum(),
    "DataSetLimpio_V2": df2.isna().sum()
}))

# Duplicados
print("\nDuplicados")
print("-----------------------------")

print("DataSetLimpio :", df1.duplicated().sum())
print("DataSetLimpio_V2 :", df2.duplicated().sum())

======================================================================
COMPARACIÓN DE DATASETS
======================================================================

Dimensiones
-----------------------------
DataSetLimpio.csv        : (805243, 9)
DataSetLimpio_V2   : (805243, 15)

Columnas
-----------------------------
Columnas iguales: False
Solo en DataSetLimpio:
set()
Solo en DataSetLimpio_V2:
{'Hora', 'Mes', 'Dia', 'Nombre_Mes', 'Año', 'Dia_Semana'}

Tipos de datos
-----------------------------

            DataSetLimpio DataSetLimpio_V2
Año                   NaN            int64
Country               str              str
Customer ID       float64          float64
Description           str              str
Dia                   NaN            int64
Dia_Semana            NaN              str
Hora                  NaN            int64
Invoice             int64            int64
InvoiceDate           str              str
Mes                   NaN            int64
Nombre_Mes            NaN              str
Price             float64          float64
Quantity            int64            int64
StockCode             str              str
Total             float64          float64

Valores nulos
-----------------------------

             DataSetLimpio  DataSetLimpio_V2
Año                    NaN                 0
Country                0.0                 0
Customer ID            0.0                 0
Description            0.0                 0
Dia                    NaN                 0
Dia_Semana             NaN                 0
Hora                   NaN                 0
Invoice                0.0                 0
InvoiceDate            0.0                 0
Mes                    NaN                 0
Nombre_Mes             NaN                 0
Price                  0.0                 0
Quantity               0.0                 0
StockCode              0.0                 0
Total                  0.0                 0

Duplicados
-----------------------------
DataSetLimpio : 26121
DataSetLimpio_V2 : 26121